name: mazziah
description: A new Flutter project.

publish_to: 'none'



version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  charts_flutter: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  google_fonts: ^6.1.0
  intl_phone_number_input: ^0.7.4
  otp_pin_field: ^1.2.2
  toggle_switch: ^2.1.0
  flutter_lints: ^2.0.0
  flutter_rating_bar: ^4.0.1
  charts_flutter: ^0.12.0
  flutter_screenutil: ^5.9.0


flutter:

  uses-material-design: true

  assets:
     - lib/assets/mazziah.png
     - lib/assets/logoicon.png
     - lib/assets/bg.png
     - lib/assets/flag.png
     - lib/assets/pp.png
     - lib/assets/donation.png
     - lib/assets/branch.png
     - lib/assets/map.png
     - lib/assets/twitter.png
     - lib/assets/coin.png
     - lib/assets/rec/r1.png
     - lib/assets/rec/r2.png
     - lib/assets/rec/r3.png
     - lib/assets/theme.png
     - lib/assets/newPur.png
     - lib/assets/brcAnalysis.png
     - lib/assets/brcWala.png


